# Initial CI Pipeline

name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-html:
    name: HTML Validation (W3C)
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -name: Validate HTML files with W3C API
      run: |
          find source -name "*.html" | while read file; do
            echo "Validating $file"
            curl --silent --output result.txt --write-out "%{http_code}" \
              -F "uploaded_file=@$file;type=text/html" \
              https://validator.w3.org/nu/?out=text > status.txt

            if ! grep -q "200" status.txt; then
              echo "❌ Validation failed for $file"
              cat result.txt
              exit 1
            else
              echo "✅ $file passed validation"
            fi
          done
    
  # unit-tests:
  # jsdoc-build:
    
