# Initial CI Pipeline

name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-html:
    name: HTML Validation (W3C)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate HTML files with W3C API
        run: |
          find source -name "*.html" | while read file; do
            echo "Validating $file"
            curl --silent --output validator-result.txt \
              -F "uploaded_file=@$file;type=text/html" \
              https://validator.w3.org/nu/?out=text
            
            echo "----- W3C Validator Resopnse for $file -----"
            cat validator-result.txt

            if grep -q "Error:" validator-result.txt; then
              echo "Validation failed for $file"
              cat validator-result.txt
              exit 1
            else
              echo "Validation passed for $file"
            fi
          done
    
  # unit-tests:
  # jsdoc-build:
    
